### PR TITLE
Rebased and added SimpleFi + StakeDAO changes

### PR DESCRIPTION
**Pull request by raphael-mazet**
Here's a new PR, rebasing conflicting changes you made to the main branch earlier to day and adding changes requested by StakeDAO @Tommytrg @gabaldon @aesedepece.

### CODE REVIEW

**Review by Tommytrg — APPROVED** [review]

**Comment by Tommytrg** [comment]
@raphael-mazet looks good to me!

**Comment by raphael-mazet** [comment]
> @raphael-mazet looks good to me!

Awesome thanks! We're getting requests for parties that don't exist as we're getting closer to the date. Clearly this is going to be a week to remember!

**Comment by aesedepece** [comment]
Merged!

**Comment by raphael-mazet** [comment]
🚀🙏🏻

**Pull request merged**
